sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
before_install:
  - git fetch origin refs/heads/master:refs/heads/master
  - if [[ "$TRAVIS_PULL_REQUEST_BRANCH" ]] ; then git checkout -b "$TRAVIS_PULL_REQUEST_BRANCH" ; fi
  - if [[ "$TRAVIS_NODE_VERSION" == 4 ]] ; then npm install --global npm@3.x.x ; fi
